const C=LearningCore,$=s=>document.querySelector(s);
const cats=[{e:'🧺',n:'衣物篮'},{e:'📚',n:'书架'},{e:'🧸',n:'玩具箱'},{e:'✏️',n:'文具盒'}];
const pool=[[['🧦','袜子'],['👕','上衣'],['🧢','帽子']],[['📕','故事书'],['📘','图画书'],['📗','科学书']],[['🪀','溜溜球'],['🧩','拼图'],['⚽','皮球']],[['🖍️','蜡笔'],['✂️','剪刀'],['📏','尺子']]];
const configs=[[0,2,1,3],[0,0,2,2,1],[3,1,3,2,0],[2,1,0,3,2,1],[0,1,2,3,0,1],[3,2,1,0,3,2],[1,1,2,0,3,3,2],[0,2,3,1,0,2,3],[3,0,1,2,1,3,0,2],[0,1,2,3,2,1,0,3,2,1]];
let level=0,items=[],placed=[],selected=null;const E={progress:$('#progress'),pill:$('#pill'),task:$('#task'),mess:$('#mess'),zones:$('#zones'),feedback:$('#feedback'),overlay:$('#overlay'),result:$('#resultText'),next:$('#next')};
function start(){level=0;C.show('game');load()}
function load(){const used=[0,0,0,0];items=configs[level].map(cat=>{const p=pool[cat][used[cat]++%3];return{cat,e:p[0],n:p[1]}});placed=Array(items.length).fill(false);selected=null;E.overlay.classList.remove('show');E.pill.textContent=`第${level+1}关`;E.task.textContent=level<4?'把物品放回正确位置':'按类别整理，最后检查有没有遗漏';C.progress(E.progress,level);render();C.feedback(E.feedback,'点一个物品，再点它应该回去的位置。');setTimeout(()=>C.speak(`请把${items.map(x=>x.n).join('、')}放回正确位置`),350)}
function render(){E.mess.innerHTML=items.map((x,i)=>`<button class="mess-item${selected===i?' selected':''}${placed[i]?' used':''}" data-i="${i}">${x.e}</button>`).join('');E.mess.querySelectorAll('button').forEach(b=>b.onclick=()=>{if(!placed[+b.dataset.i]){selected=+b.dataset.i;render();C.feedback(E.feedback,`拿起了${items[selected].n}，它应该放在哪里？`)}});E.zones.innerHTML=cats.map((c,i)=>`<button class="zone" data-cat="${i}">${c.e}<small>${c.n}</small><span>${items.map((x,j)=>placed[j]&&x.cat===i?x.e:'').join('')}</span></button>`).join('');E.zones.querySelectorAll('button').forEach(b=>b.onclick=put(+b.dataset.cat))}
function put(cat){return()=>{if(selected===null)return;const x=items[selected];if(x.cat===cat){placed[selected]=true;C.feedback(E.feedback,`${x.n}放对啦！`,'good');selected=null;render()}else{C.feedback(E.feedback,`${x.n}不住在${cats[cat].n}，再找找。`,'hint');C.speak(`${x.n}不放在这里，再找找`)}}}
function check(){if(placed.every(Boolean)){C.win({overlay:E.overlay,textEl:E.result,text:`你整理了${items.length}件物品，而且一件都没有漏。`,nextButton:E.next,level});return}C.feedback(E.feedback,`还有${placed.filter(x=>!x).length}件物品没有收好，请检查一下。`,'hint')}
function hint(){const i=placed.findIndex(x=>!x);if(i<0)return;placed[i]=true;selected=null;render();C.feedback(E.feedback,`${items[i].n}应该放进${cats[items[i].cat].n}。`,'good');C.speak(`${items[i].n}应该放进${cats[items[i].cat].n}`)}
function next(){if(level===9){E.overlay.classList.remove('show');C.show('finish');C.speak('恭喜你成为整理小管家');return}level++;load()}
$('#start').onclick=start;$('#again').onclick=start;$('#home').onclick=()=>C.show('welcome');$('#listen').onclick=()=>C.speak(`请把${items.filter((_,i)=>!placed[i]).map(x=>x.n).join('、')}放回正确位置`);$('#reset').onclick=load;$('#hint').onclick=hint;$('#check').onclick=check;E.next.onclick=next;$('#soundW').onclick=$('#soundG').onclick=()=>C.toggle($('#soundW'),$('#soundG'));
