const animals=[{emoji:"🐰",name:"小兔子"},{emoji:"🐻",name:"小熊"},{emoji:"🦊",name:"小狐狸"},{emoji:"🐼",name:"小熊猫"}];
const sudokuLevels=[
{puzzle:"321001231032230.",solution:"3210012310322301"},{puzzle:"10232310320.0132",solution:"1023231032010132"},{puzzle:"301212300.2.2103",solution:"3012123003212103"},{puzzle:"0.12.20330212130",solution:"0312120330212130"},{puzzle:"0.2112303.1.2103",solution:"0321123030122103"},
{puzzle:"10.3320123..013.",solution:"1023320123100132"},{puzzle:"321001.3230...32",solution:"3210012323011032"},{puzzle:"2..31.20.231.102",solution:"2013132002313102"},{puzzle:"..20203..2.31302",solution:"3120203102131302"},{puzzle:"..300321.0.2.10.",solution:"1230032130122103"},
{puzzle:"1.233..123.001..",solution:"1023320123100132"},{puzzle:"..13.3...10.0231",solution:"2013132031020231"},{puzzle:".1....01.03.3210",solution:"0123230110323210"},{puzzle:".023...10.322...",solution:"1023320101322310"},{puzzle:"1..330.1..3..3.2",solution:"1203302121300312"},
{puzzle:"......13.231.32.",solution:"3102201302311320"},{puzzle:"3..2.2.1..131...",solution:"3102023120131320"},{puzzle:"..2.0....0311...",solution:"3120021320311302"},{puzzle:"2..1.1...21...0.",solution:"2031312002131302"},{puzzle:".0..2....123..1.",solution:"1032230101233210"}
];
const sudokuState={level:0,startLevel:0,grid:[],given:[],selectedCell:null,selectedAnimal:null,mistakes:0,sound:true,locked:false};
const sudokuEl={welcome:document.querySelector("#sudokuWelcome"),game:document.querySelector("#sudokuGame"),finish:document.querySelector("#sudokuFinish"),start:document.querySelector("#sudokuStart"),challenge:document.querySelector("#sudokuChallengeStart"),home:document.querySelector("#sudokuHome"),again:document.querySelector("#sudokuAgain"),next:document.querySelector("#sudokuNext"),board:document.querySelector("#sudokuBoard"),tray:document.querySelector("#animalTray"),progress:document.querySelector("#sudokuProgress"),remaining:document.querySelector("#remainingCount"),levelName:document.querySelector("#sudokuLevelName"),task:document.querySelector("#sudokuTask"),feedback:document.querySelector("#sudokuFeedback"),hint:document.querySelector("#sudokuHint"),overlay:document.querySelector("#sudokuOverlay"),resultText:document.querySelector("#sudokuResultText"),finishKicker:document.querySelector("#sudokuFinishKicker"),finishText:document.querySelector("#sudokuFinishText"),soundWelcome:document.querySelector("#sudokuSoundWelcome"),soundGame:document.querySelector("#sudokuSoundGame")};
function showSudokuScreen(name){[sudokuEl.welcome,sudokuEl.game,sudokuEl.finish].forEach(x=>x.classList.remove("is-active"));sudokuEl[name].classList.add("is-active");window.scrollTo({top:0,behavior:"smooth"})}
function difficultyName(level){return level<5?"热身":level<10?"进阶":level<15?"推理":"挑战"}
function startSudoku(startLevel=0){sudokuState.level=startLevel;sudokuState.startLevel=startLevel;showSudokuScreen("game");loadSudokuLevel()}
function loadSudokuLevel(){const level=sudokuLevels[sudokuState.level];sudokuState.grid=[...level.puzzle].map(x=>x==="."?null:Number(x));sudokuState.given=sudokuState.grid.map(x=>x!==null);sudokuState.selectedCell=null;sudokuState.selectedAnimal=null;sudokuState.mistakes=0;sudokuState.locked=false;sudokuEl.overlay.classList.remove("show");sudokuEl.levelName.textContent=`第${sudokuState.level+1}关 · ${difficultyName(sudokuState.level)}`;sudokuEl.task.textContent=sudokuState.level<5?"找出缺少的那只动物":"让每行、每列和小区域都不重复";renderSudoku();renderTray();renderSudokuProgress();setSudokuFeedback("仔细看看哪只动物还没有出现。");setTimeout(speakSudokuTask,350)}
function renderSudoku(){sudokuEl.board.innerHTML="";sudokuState.grid.forEach((value,index)=>{const cell=document.createElement("button");cell.type="button";cell.className=`sudoku-cell${sudokuState.given[index]?" given":""}${value===null?" empty":""}${sudokuState.selectedCell===index?" selected":""}`;cell.dataset.index=index;cell.setAttribute("role","gridcell");cell.setAttribute("aria-label",value===null?`第${Math.floor(index/4)+1}行第${index%4+1}列，空格`:`第${Math.floor(index/4)+1}行第${index%4+1}列，${animals[value].name}`);if(value!==null)cell.textContent=animals[value].emoji;if(!sudokuState.given[index])cell.addEventListener("click",()=>selectCell(index));sudokuEl.board.append(cell)});updateRemaining()}
function renderTray(){sudokuEl.tray.innerHTML="";animals.forEach((animal,value)=>{const button=document.createElement("button");button.type="button";button.className=`animal-button${sudokuState.selectedAnimal===value?" selected":""}`;button.dataset.value=value;button.setAttribute("aria-label",`选择${animal.name}`);button.textContent=animal.emoji;button.addEventListener("click",()=>selectAnimal(value));sudokuEl.tray.append(button)})}
function renderSudokuProgress(){sudokuEl.progress.innerHTML=sudokuLevels.map((_,i)=>`<i class="${i<sudokuState.level?"done":i===sudokuState.level?"current":""}"></i>`).join("")}
function updateRemaining(){const count=sudokuState.grid.filter(x=>x===null).length;sudokuEl.remaining.textContent=`${count}格`}
function selectCell(index){if(sudokuState.locked||sudokuState.given[index]||sudokuState.grid[index]!==null)return;sudokuState.selectedCell=index;renderSudoku();highlightSelectedPeers();if(sudokuState.selectedAnimal!==null)placeAnimal(index,sudokuState.selectedAnimal);else setSudokuFeedback("选好了空格，再选一只小动物。")}
function selectAnimal(value){if(sudokuState.locked)return;sudokuState.selectedAnimal=value;renderTray();if(sudokuState.selectedCell!==null)placeAnimal(sudokuState.selectedCell,value);else setSudokuFeedback(`选中了${animals[value].name}，现在点一个空格。`)}
function placeAnimal(index,value){const answer=Number(sudokuLevels[sudokuState.level].solution[index]);const cell=sudokuEl.board.querySelector(`[data-index="${index}"]`);if(value!==answer){sudokuState.mistakes++;cell?.classList.add("wrong");setTimeout(()=>cell?.classList.remove("wrong"),450);setSudokuFeedback(`${animals[value].name}的座位不在这里，再看看这一行和这一列。`,"notice");speakSudoku("它的座位不在这里，再试试别的动物");if(sudokuState.mistakes>=2)highlightSelectedPeers();return}sudokuState.grid[index]=value;sudokuState.selectedCell=null;sudokuState.selectedAnimal=null;renderSudoku();renderTray();const correctCell=sudokuEl.board.querySelector(`[data-index="${index}"]`);correctCell?.classList.add("correct");setSudokuFeedback(`${animals[value].name}坐对位置啦！`,"good");playSudokuTone(650);if(sudokuState.grid.every(x=>x!==null))completeSudokuLevel()}
function highlightSelectedPeers(){if(sudokuState.selectedCell===null)return;const row=Math.floor(sudokuState.selectedCell/4),col=sudokuState.selectedCell%4,boxRow=Math.floor(row/2),boxCol=Math.floor(col/2);sudokuEl.board.querySelectorAll(".sudoku-cell").forEach((cell,index)=>{const r=Math.floor(index/4),c=index%4;if(r===row||c===col||(Math.floor(r/2)===boxRow&&Math.floor(c/2)===boxCol))cell.classList.add("peer")});sudokuEl.board.querySelector(`[data-index="${sudokuState.selectedCell}"]`)?.classList.add("selected")}
function hintSudoku(){if(sudokuState.locked)return;const index=sudokuState.grid.findIndex(x=>x===null);if(index<0)return;sudokuState.selectedCell=index;sudokuState.selectedAnimal=Number(sudokuLevels[sudokuState.level].solution[index]);setSudokuFeedback("猫头鹰帮你想好这一格啦！","good");placeAnimal(index,sudokuState.selectedAnimal)}
function completeSudokuLevel(){sudokuState.locked=true;playSudokuSuccess();sudokuEl.resultText.textContent=`第${sudokuState.level+1}关完成！所有动物都坐在正确位置。`;sudokuEl.next.querySelector("span").textContent=sudokuState.level===sudokuLevels.length-1?"领取奖章":"下一关";setTimeout(()=>{sudokuEl.overlay.classList.add("show");speakSudoku("全部坐对啦，逻辑真清楚")},450)}
function nextSudokuLevel(){if(sudokuState.level===sudokuLevels.length-1){sudokuEl.overlay.classList.remove("show");const completed=sudokuLevels.length-sudokuState.startLevel;sudokuEl.finishKicker.textContent=`${completed}关全部完成`;sudokuEl.finishText.textContent=`你解开了${completed}个动物座位谜题！`;showSudokuScreen("finish");speakSudoku("恭喜你成为森林逻辑达人");return}sudokuState.level++;loadSudokuLevel()}
function setSudokuFeedback(text,type=""){sudokuEl.feedback.textContent=text;sudokuEl.feedback.className=`feedback${type?` ${type}`:""}`}
function speakSudokuTask(){speakSudoku(`第${sudokuState.level+1}关，${sudokuEl.task.textContent}`)}
function speakSudoku(text){if(!sudokuState.sound||!("speechSynthesis"in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="zh-CN";u.rate=.84;u.pitch=1.14;speechSynthesis.speak(u)}
function toggleSudokuSound(){sudokuState.sound=!sudokuState.sound;if(!sudokuState.sound&&"speechSynthesis"in window)speechSynthesis.cancel();sudokuEl.soundWelcome.textContent=sudokuState.sound?"🔊 声音开着":"🔇 声音关了";sudokuEl.soundWelcome.setAttribute("aria-label",sudokuState.sound?"关闭声音":"打开声音");sudokuEl.soundGame.textContent=sudokuState.sound?"🔊":"🔇";sudokuEl.soundGame.setAttribute("aria-label",sudokuState.sound?"关闭声音":"打开声音")}
function playSudokuTone(freq){if(!sudokuState.sound)return;try{const a=new(window.AudioContext||window.webkitAudioContext)(),o=a.createOscillator(),g=a.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.11,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.26);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+.27)}catch(_){}}
function playSudokuSuccess(){[523,659,784].forEach((f,i)=>setTimeout(()=>playSudokuTone(f),i*110))}
sudokuEl.start.addEventListener("click",()=>startSudoku(0));sudokuEl.challenge.addEventListener("click",()=>startSudoku(10));sudokuEl.again.addEventListener("click",()=>startSudoku(sudokuState.startLevel));sudokuEl.home.addEventListener("click",()=>showSudokuScreen("welcome"));sudokuEl.hint.addEventListener("click",hintSudoku);sudokuEl.next.addEventListener("click",nextSudokuLevel);sudokuEl.soundWelcome.addEventListener("click",toggleSudokuSound);sudokuEl.soundGame.addEventListener("click",toggleSudokuSound);
