CREATE TABLE IF NOT EXISTS stories (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  story_key VARCHAR(64) NOT NULL,
  source VARCHAR(16) NOT NULL,
  domain VARCHAR(16) NOT NULL,
  age_label VARCHAR(20) NOT NULL,
  duration_label VARCHAR(20) NOT NULL,
  title VARCHAR(80) NOT NULL,
  summary VARCHAR(255) NOT NULL,
  learning_goal VARCHAR(255) NOT NULL,
  story_content JSON NOT NULL,
  questions JSON NOT NULL,
  action_text VARCHAR(500) NOT NULL,
  parent_tip VARCHAR(500) NOT NULL,
  device_id VARCHAR(64) NULL,
  model_name VARCHAR(80) NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE INDEX uk_stories_story_key (story_key),
  INDEX idx_stories_source_domain_status (source, domain, status),
  INDEX idx_stories_device_created (device_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
