const lineupAnimals=[{emoji:"🐰",name:"小兔子"},{emoji:"🐻",name:"小熊"},{emoji:"🦊",name:"小狐狸"},{emoji:"🐼",name:"小熊猫"},{emoji:"🦁",name:"小狮子"}];
const lineupConfigs=[
{solution:[0,1,2],mode:"easy"},{solution:[2,0,1],mode:"easy"},{solution:[1,2,0],mode:"easy"},{solution:[0,2,1],mode:"easy"},{solution:[1,0,2],mode:"easy"},
{solution:[0,1,2,3],mode:"medium"},{solution:[2,0,3,1],mode:"medium"},{solution:[1,3,0,2],mode:"medium"},{solution:[3,2,1,0],mode:"medium"},{solution:[0,3,1,2],mode:"medium"},{solution:[2,1,0,3],mode:"medium"},{solution:[1,0,3,2],mode:"medium"},{solution:[3,1,2,0],mode:"medium"},
{solution:[0,1,2,3,4],mode:"hard"},{solution:[4,2,0,3,1],mode:"hard"},{solution:[1,3,4,0,2],mode:"hard"},{solution:[2,0,4,1,3],mode:"hard"},{solution:[3,4,1,2,0],mode:"hard"},{solution:[0,2,4,3,1],mode:"hard"},{solution:[4,1,3,0,2],mode:"hard"}
];
function permutations(items){if(items.length<2)return[[...items]];return items.flatMap((item,i)=>permutations(items.filter((_,j)=>j!==i)).map(rest=>[item,...rest]))}
function seededShuffle(items,seed){const a=[...items];let s=seed>>>0;const random=()=>((s=Math.imul(s,1664525)+1013904223>>>0)/4294967296);for(let i=a.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function clueMatches(order,clue){const pos=id=>order.indexOf(id);if(clue.type==="first")return pos(clue.a)===0;if(clue.type==="last")return pos(clue.a)===order.length-1;if(clue.type==="left")return pos(clue.a)<pos(clue.b);if(clue.type==="immediate")return pos(clue.b)===pos(clue.a)+1;if(clue.type==="adjacent")return Math.abs(pos(clue.a)-pos(clue.b))===1;if(clue.type==="between"){const p=pos(clue.a),x=pos(clue.b),y=pos(clue.c);return p>Math.min(x,y)&&p<Math.max(x,y)}return false}
function buildCluePool(solution,mode){const pool=[],n=solution.length;pool.push({type:"first",a:solution[0]},{type:"last",a:solution[n-1]});for(let i=0;i<n;i++)for(let j=i+1;j<n;j++)pool.push({type:"left",a:solution[i],b:solution[j]});for(let i=0;i<n-1;i++){pool.push({type:"immediate",a:solution[i],b:solution[i+1]});pool.push({type:"adjacent",a:solution[i],b:solution[i+1]})}for(let i=1;i<n-1;i++)pool.push({type:"between",a:solution[i],b:solution[i-1],c:solution[i+1]});const allowed=mode==="easy"?["first","last","immediate"]:mode==="medium"?["first","last","left","immediate","adjacent"]:["first","last","left","adjacent","between","immediate"];return pool.filter(c=>allowed.includes(c.type))}
function buildLevelClues(config,index){const animals=[...config.solution],all=permutations(animals);let candidates=all,chosen=[],pool=seededShuffle(buildCluePool(config.solution,config.mode),920+index*71);while(candidates.length>1){let bestIndex=-1,bestNext=candidates;pool.forEach((clue,i)=>{const next=candidates.filter(order=>clueMatches(order,clue));if(next.length>0&&next.length<bestNext.length){bestIndex=i;bestNext=next}});if(bestIndex<0)break;chosen.push(pool[bestIndex]);pool.splice(bestIndex,1);candidates=bestNext}if(candidates.length!==1)throw new Error(`第${index+1}关线索不唯一`);return chosen}
const lineupLevels=lineupConfigs.map((config,index)=>({...config,clues:buildLevelClues(config,index)}));
const lineupState={level:0,startLevel:0,arrangement:[],selected:null,sound:true,locked:false};
const lineupEl={welcome:document.querySelector("#lineupWelcome"),game:document.querySelector("#lineupGame"),finish:document.querySelector("#lineupFinish"),start:document.querySelector("#lineupStart"),challenge:document.querySelector("#lineupChallengeStart"),home:document.querySelector("#lineupHome"),again:document.querySelector("#lineupAgain"),next:document.querySelector("#lineupNext"),progress:document.querySelector("#lineupProgress"),count:document.querySelector("#animalCount"),levelName:document.querySelector("#lineupLevelName"),task:document.querySelector("#lineupTask"),clues:document.querySelector("#clueList"),slots:document.querySelector("#queueSlots"),tray:document.querySelector("#lineupTray"),feedback:document.querySelector("#lineupFeedback"),playAll:document.querySelector("#playAllClues"),reset:document.querySelector("#resetLineup"),hint:document.querySelector("#hintLineup"),check:document.querySelector("#checkLineup"),overlay:document.querySelector("#lineupOverlay"),resultText:document.querySelector("#lineupResultText"),resultAnimals:document.querySelector("#resultAnimals"),finishKicker:document.querySelector("#lineupFinishKicker"),finishText:document.querySelector("#lineupFinishText"),soundWelcome:document.querySelector("#lineupSoundWelcome"),soundGame:document.querySelector("#lineupSoundGame")};
function showLineupScreen(name){[lineupEl.welcome,lineupEl.game,lineupEl.finish].forEach(x=>x.classList.remove("is-active"));lineupEl[name].classList.add("is-active");window.scrollTo({top:0,behavior:"smooth"})}
function lineupDifficulty(level){return level<5?"热身":level<13?"进阶":"挑战"}
function startLineup(startLevel=0){lineupState.level=startLevel;lineupState.startLevel=startLevel;showLineupScreen("game");loadLineupLevel()}
function loadLineupLevel(){const level=lineupLevels[lineupState.level];lineupState.arrangement=Array(level.solution.length).fill(null);lineupState.selected=null;lineupState.locked=false;lineupEl.overlay.classList.remove("show");lineupEl.levelName.textContent=`第${lineupState.level+1}关 · ${lineupDifficulty(lineupState.level)}`;lineupEl.task.textContent=`根据语音线索，排好${level.solution.length}只动物`;lineupEl.count.textContent=`${level.solution.length}只`;renderLineupProgress();renderClues();renderQueue();renderLineupTray();setLineupFeedback("先听听线索，再开始排队吧！");playAllClues()}
function renderLineupProgress(){lineupEl.progress.innerHTML=lineupLevels.map((_,i)=>`<i class="${i<lineupState.level?"done":i===lineupState.level?"current":""}"></i>`).join("")}
function clueText(clue){const A=lineupAnimals[clue.a].name,B=clue.b===undefined?"":lineupAnimals[clue.b].name,C=clue.c===undefined?"":lineupAnimals[clue.c].name;if(clue.type==="first")return `${A}站在最左边`;if(clue.type==="last")return `${A}站在最右边`;if(clue.type==="left")return `${A}站在${B}左边`;if(clue.type==="immediate")return `${A}紧挨着站在${B}左边`;if(clue.type==="adjacent")return `${A}和${B}挨在一起`;return `${A}站在${B}和${C}中间`}
function clueVisual(clue){const a=lineupAnimals[clue.a].emoji,b=clue.b===undefined?"":lineupAnimals[clue.b].emoji,c=clue.c===undefined?"":lineupAnimals[clue.c].emoji;if(clue.type==="first")return `<i>最左</i><span>${a}</span>`;if(clue.type==="last")return `<span>${a}</span><i>最右</i>`;if(clue.type==="left")return `<span>${a}</span><i>◀</i><span>${b}</span>`;if(clue.type==="immediate")return `<span>${a}</span><i>紧挨 ➜</i><span>${b}</span>`;if(clue.type==="adjacent")return `<span>${a}</span><i>↔</i><span>${b}</span>`;return `<span>${b}</span><i>—</i><span>${a}</span><i>—</i><span>${c}</span>`}
function renderClues(){lineupEl.clues.innerHTML="";lineupLevels[lineupState.level].clues.forEach((clue,index)=>{const card=document.createElement("div");card.className="clue-card";card.dataset.clue=index;card.innerHTML=`<div class="clue-visual">${clueVisual(clue)}</div><span class="clue-text">${clueText(clue)}</span><button class="clue-sound" type="button" aria-label="播报线索：${clueText(clue)}">🔊</button>`;card.querySelector("button").addEventListener("click",()=>speakLineup(clueText(clue)));lineupEl.clues.append(card)})}
function renderQueue(){lineupEl.slots.style.setProperty("--slot-count",lineupState.arrangement.length);lineupEl.slots.innerHTML="";lineupState.arrangement.forEach((animalId,index)=>{const slot=document.createElement("button");slot.type="button";slot.className=`queue-slot${animalId!==null?" filled":""}`;slot.dataset.slot=index;slot.dataset.position=`${index+1}`;slot.setAttribute("aria-label",animalId===null?`第${index+1}个位置，空位`:`第${index+1}个位置，${lineupAnimals[animalId].name}`);if(animalId!==null)slot.textContent=lineupAnimals[animalId].emoji;slot.addEventListener("click",()=>chooseSlot(index));lineupEl.slots.append(slot)})}
function renderLineupTray(){const used=new Set(lineupState.arrangement.filter(x=>x!==null));lineupEl.tray.innerHTML="";lineupLevels[lineupState.level].solution.slice().sort((a,b)=>a-b).forEach(id=>{const button=document.createElement("button");button.type="button";button.className=`animal-button${used.has(id)?" used":""}${lineupState.selected===id?" selected":""}`;button.setAttribute("aria-label",`选择${lineupAnimals[id].name}`);button.textContent=lineupAnimals[id].emoji;button.disabled=used.has(id);button.addEventListener("click",()=>{lineupState.selected=id;renderLineupTray();setLineupFeedback(`选中了${lineupAnimals[id].name}，点一个位置。`)});lineupEl.tray.append(button)})}
function chooseSlot(index){if(lineupState.locked)return;const current=lineupState.arrangement[index];if(lineupState.selected===null){if(current!==null){lineupState.arrangement[index]=null;lineupState.selected=current;renderQueue();renderLineupTray();setLineupFeedback(`拿起了${lineupAnimals[current].name}，请换个位置。`)}return}lineupState.arrangement[index]=lineupState.selected;lineupState.selected=current;renderQueue();renderLineupTray();if(lineupState.arrangement.every(x=>x!==null))setLineupFeedback("队伍排满啦，按“检查队伍”看看！","good");else setLineupFeedback("继续听线索，安排下一只动物。")}
function checkCurrentLineup(){if(lineupState.arrangement.some(x=>x===null)){setLineupFeedback("还有空位，请先让每只动物都站好。","notice");speakLineup("还有动物没有站好");return}const level=lineupLevels[lineupState.level],failed=level.clues.findIndex(clue=>!clueMatches(lineupState.arrangement,clue));if(failed>=0){lineupEl.clues.querySelectorAll(".clue-card").forEach(x=>x.classList.remove("failed"));const card=lineupEl.clues.querySelector(`[data-clue="${failed}"]`);card?.classList.add("failed");const text=clueText(level.clues[failed]);setLineupFeedback(`再听听这条线索：${text}`,"notice");speakLineup(text);return}completeLineupLevel()}
function resetLineup(){lineupState.arrangement.fill(null);lineupState.selected=null;renderQueue();renderLineupTray();setLineupFeedback("队伍清空了，重新听线索再试试。")}
function hintLineup(){if(lineupState.locked)return;const solution=lineupLevels[lineupState.level].solution;let index=lineupState.arrangement.findIndex((value,i)=>value!==solution[i]);if(index<0)return;const correct=solution[index],currentPos=lineupState.arrangement.indexOf(correct),displaced=lineupState.arrangement[index];if(currentPos>=0)lineupState.arrangement[currentPos]=displaced;lineupState.arrangement[index]=correct;lineupState.selected=null;renderQueue();renderLineupTray();lineupEl.slots.querySelector(`[data-slot="${index}"]`)?.classList.add("correct");setLineupFeedback(`${lineupAnimals[correct].name}站对一个位置啦！`,"good");speakLineup(`${lineupAnimals[correct].name}站在第${index+1}个位置`)}
function completeLineupLevel(){lineupState.locked=true;const level=lineupLevels[lineupState.level];lineupEl.resultAnimals.textContent=level.solution.map(id=>lineupAnimals[id].emoji).join("");lineupEl.resultText.textContent=`第${lineupState.level+1}关完成，所有语音线索都满足了！`;lineupEl.next.querySelector("span").textContent=lineupState.level===lineupLevels.length-1?"领取奖章":"下一关";playLineupSuccess();setTimeout(()=>{lineupEl.overlay.classList.add("show");speakLineup("队伍排好啦，每条线索都正确")},450)}
function nextLineupLevel(){if(lineupState.level===lineupLevels.length-1){lineupEl.overlay.classList.remove("show");const completed=lineupLevels.length-lineupState.startLevel;lineupEl.finishKicker.textContent=`${completed}关全部完成`;lineupEl.finishText.textContent=`你听懂了所有线索，完成了${completed}次排队！`;showLineupScreen("finish");speakLineup("恭喜你成为森林线索达人");return}lineupState.level++;loadLineupLevel()}
function playAllClues(){const text=lineupLevels[lineupState.level].clues.map(clueText).join("。");speakLineup(`请听线索。${text}`)}
function setLineupFeedback(text,type=""){lineupEl.feedback.textContent=text;lineupEl.feedback.className=`feedback${type?` ${type}`:""}`}
function speakLineup(text){if(!lineupState.sound)return;window.PlaymoriVoice.speak(text,{rate:.78,pitch:1.04})}
function toggleLineupSound(){lineupState.sound=!lineupState.sound;if(!lineupState.sound)window.PlaymoriVoice.cancel();lineupEl.soundWelcome.textContent=lineupState.sound?"🔊 声音开着":"🔇 声音关了";lineupEl.soundWelcome.setAttribute("aria-label",lineupState.sound?"关闭声音":"打开声音");lineupEl.soundGame.textContent=lineupState.sound?"🔊":"🔇";lineupEl.soundGame.setAttribute("aria-label",lineupState.sound?"关闭声音":"打开声音")}
function playLineupTone(f){if(!lineupState.sound)return;try{const a=new(window.AudioContext||window.webkitAudioContext)(),o=a.createOscillator(),g=a.createGain();o.frequency.value=f;g.gain.setValueAtTime(.11,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.26);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+.27)}catch(_){}}
function playLineupSuccess(){[523,659,784].forEach((f,i)=>setTimeout(()=>playLineupTone(f),i*110))}
lineupEl.start.addEventListener("click",()=>startLineup(0));lineupEl.challenge.addEventListener("click",()=>startLineup(10));lineupEl.again.addEventListener("click",()=>startLineup(lineupState.startLevel));lineupEl.home.addEventListener("click",()=>showLineupScreen("welcome"));lineupEl.playAll.addEventListener("click",playAllClues);lineupEl.reset.addEventListener("click",resetLineup);lineupEl.hint.addEventListener("click",hintLineup);lineupEl.check.addEventListener("click",checkCurrentLineup);lineupEl.next.addEventListener("click",nextLineupLevel);lineupEl.soundWelcome.addEventListener("click",toggleLineupSound);lineupEl.soundGame.addEventListener("click",toggleLineupSound);
